
import database
import bpms_service

names = [
    "JUAN PABLO BUSTAMANTE VALENCIA", "YENY PAOLA SUAREZ BARRIOS", "VALENTINA MARTINEZ OTALVARO",
    "CAMILA RIOS MARTINEZ", "LINA MARIA RAMIREZ GARCIA", "ISABEL CRISTINA HERNANDEZ ACOSTA",
    "OSCAR FABIAN ALZATE AGUDELO", "MONICA ISABEL ARROYAVE ARCILA", "PAULA ANDREA ALVAREZ GIRALDO",
    "JHOAN ORLANDO ARANGO JARAMILLO", "LIGIA RESTREPO ARROYAVE", "GLADYS GIRALDO SALAZAR",
    "JULIAN ALBERTO ZULUAGA OTALVARO", "LAURA MARIA JURADO GALLEGO", "ANA MARIA LONDOÑO MONTOYA",
    "MANUEL ALEJANDRO GALINDO MUÑOZ", "MARY MAR POSADA MUNERA", "SHIRLEY ANDREA MARIN LOPEZ",
    "MAURICIO RAMIREZ OTALVARO", "YESID LEON OCHOA LOPEZ", "ALBA PATRICIA OTALVARO CORREA",
    "JUAN MANUEL MARTINEZ OTALVARO", "JUAN CAMILO GARCIA ATEHORTUA", "VALENTINA PATIÑO SERNA",
    "ANDERSON RIOS LOPEZ", "LEIDY JHOANNA VALENCIA VALENCIA", "DAISSY FRANCELLA RIOS GARCIA",
    "ANDRES FELIPE ECHEVERRI GALLEGO", "BIANIZ FAHIRUT CASTAÑEDA GARCIA", "CAROLINA BEDOYA TOBON",
    "JONATHAN ALZATE JIMENEZ", "BIBIANA MARIA GARCIA GOMEZ", "JORGE ANDRES ARBOLEDA",
    "MARIA CLEOFE MORALES OSPINA", "LEIDY JOHANA GARCES URREA", "JUAN PABLO JIMENEZ OTALVARO",
    "MANUELA GOMEZ ARIAS", "JOHAN STIVEN CARDONA URREA", "DAVID AUGUSTO DUQUE LOPEZ",
    "JENNY PATRICIA ARIZA LOPEZ", "MARIA GLADYS VALENCIA ESCUDERO", "MARGARITA RAMIREZ RAMIREZ",
    "MARIA TERESA FLOREZ BUITRAGO", "DIEGO MAURICIO RENDON CASTAÑO", "ISABELLA RENDON LOPEZ",
    "DIDIER SANCHEZ LOPEZ", "CARLOS ANDRES QUINTERO JIMENEZ", "SARA YULIETH RIOS CARDONA",
    "KATHERINE JOHANNA GARCIA GUTIERREZ", "DIANA PATRICIA MACHADO BEDOYA", "WILLIAM ALBERTO GONZALEZ ARROYAVE",
    "ERIKA MARIA DUQUE BETANCUR", "GLORIA EUGENIA RENDON OROZCO", "OURIEL DE JESUS RENDON ALVAREZ",
    "ADRIANA MARCELA ZULUAGA VARGAS", "ALBA SILENY REYES QUINTERO", "ALCIDES ANTONIO GOMEZ LOAIZA",
    "ALEJANDRO ALBERTO GIRALDO OROZCO", "ANGELA MARIA LONDOÑO ARBOLEDA", "ANGIE MELISSA DUQUE ATEHORTUA",
    "ANGIE ZULUAGA CANO", "BEATRIZ ELENA OSPINA GARZON", "BIBIANA MARCELA OSORIO TOVAR",
    "CAMILO ANDRES MONTOYA BUSTAMANTE", "CRISTIAN DAVID OSPINA OSPINA", "DANIELA DIEZ ECHEVERRI",
    "DARY ESTEFANIA PARRA MARTINEZ", "DIANA CRISTINA GARCIA GUARIN", "DIANA MARCELA CORREA CASTAÑEDA",
    "DIANA MARIA OROZCO MARIN", "DIANA PATRICIA HERNANDEZ URIBE", "DORA ALBA GUZMAN VALENCIA",
    "ERIKA SERNA SANCHEZ", "GLADIS MARGOT PEREZ ECHAVARRIA", "GLORIA EUGENIA GUARIN SILVA",
    "GLORIA ISABEL RENDON CARRILLO", "HECTOR FABIAN PUERTA CORDOBA", "HERNAN DARIO GOMEZ CASTAÑO",
    "JESUS ANTONIO POSADA OSORIO", "JHON ALEJANDRO VALENCIA LOTERO", "JHONY ALONSO HINCAPIE BURITICA",
    "JOHN EDUAR MONTOYA GRAJALES", "JOHN FREDY LOPEZ SUAREZ", "JONATHAN ESNEIDER SANCHEZ MONTOYA",
    "JORGE LUIS CASTAEDA SALAZAR", "JUAN ANDRES CHAVES ALVAREZ", "JUAN CARLOS CARDONA",
    "JUAN DAVID CASTRO", "JUAN FELIPE ARISTIZABAL TEJADA", "JULIETH KATHERINE MEJIA ARBELAEZ",
    "LEIDY MARIA BARROS LESMES", "LUISA FERNANDA VALENCIA LARA", "MANUELA ROSERO CHAVARRIAGA",
    "MARIA FERNANDA CIFUENTES CASTAÑO", "MARIA YANET CASTAÑO GOMEZ", "MARY LUZ SERNA ARISTIZABAL",
    "MAURICIO RODRIGUEZ ORBES", "MIRIAM DISNEY CEBALLOS ZULUAGA", "MONICA MARIA SANCHEZ",
    "RODOLFO ANTONIO ARANGO CARDONA", "SERGIO HORACIO GONZALEZ JARAMILLO", "VICTOR ALFONSO GIL HOYOS",
    "VIVIANA VASQUEZ SILVA", "YULI VIVIANA CASTAÑO SANCHEZ", "YESENIA ANDREA GAVIRIA MUÑOZ",
    "ELKIN DARIO CARMONA DAVID", "ANA CAROLINA RESTREPO MONTOYA"
]

def hash_password(password):
    import hashlib
    return hashlib.sha256(password.encode()).hexdigest()

print("Iniciando depuracion...")
# 1. Limpiar tablas
database.execute("DELETE FROM hacienda_staff")
database.execute("DELETE FROM users WHERE username != 'admin'")
database.execute("DELETE FROM user_permissions WHERE user_id NOT IN (SELECT id FROM users WHERE username='admin')")

# 2. Insertar funcionarios y crear usuarios
count = 0
for full_name in names:
    norm_name = bpms_service.normalize_text(full_name)
    # Insertar en staff
    database.execute("INSERT INTO hacienda_staff(name, status, dependency, include_flag) VALUES (?,?,?,?)",
                     (norm_name, "ACTIVO", "SECRETARIA DE HACIENDA", 1))
    
    # Lógica de nombre de usuario
    parts = norm_name.split()
    if len(parts) >= 2:
        name_part = parts[0][0].lower()
        surname_part = parts[1].lower()
        base_un = f"{name_part}{surname_part}"
        
        un = base_un
        # Verificar si existe para evitar conflictos (aunque en esta carga limpia no deberia pasar)
        exists = database.query_one("SELECT id FROM users WHERE username=?", (un,))
        if exists and len(parts) >= 3:
            un = f"{base_un}{parts[2][0].lower()}"
            
        # Crear usuario
        database.execute("INSERT INTO users(username, password_hash, role, full_name, is_active, force_password_change) VALUES (?,?,?,?,?,?)",
                         (un, hash_password("123456"), "user", norm_name, 1, 1))
        
        # Asignar permisos iniciales (sus propios radicados)
        uid = database.query_one("SELECT id FROM users WHERE username=?", (un,))["id"]
        database.execute("INSERT INTO user_permissions(user_id, funcionario_name) VALUES (?,?)", (uid, norm_name))
        count += 1

print(f"Depuracion completada. Se cargaron {len(names)} funcionarios y se crearon {count} usuarios.")
